### ISSUE TITLE
Have some problem with import library

### ISSUE THREAD

**Issue by Banonevar** [unofficial-dlive-tv-api/dlivetv-unofficial-api-js#5] opened 2019-04-23 19:05 UTC
**Describe the bug**
I can't run this library, for some reason got error:
```
node test
\node_modules\dlivetv-unofficial-api\index.js:1
import DliveInit from './dliveInit'
       ^^^^^^^^^
SyntaxError: Unexpected identifier
```
**To Reproduce**
Maybe i just some noob and need help with setup

**Expected behavior**
Should work

**Screenshots**

**Development runtime (please complete the following information):**
 - OS: Windows 10
 - Browser: doesn't matter i guess
 - Node & NPM version: v11.13.0, 6.7.0

**Additional context**

**Comment by timedotcc** [comment] 2019-04-23 19:08
You have to use Babel. 
https://babeljs.io/docs/en/babel-node

**Comment by Banonevar** [comment] 2019-04-23 19:10
@timedotcc thank you for quick answer, can you add some info to readme then? for guys like me

**Comment by Banonevar** [comment] 2019-04-23 19:15
@timedotcc hm..
```
npx babel-node app.js
Unhandled Rejection at:  Promise {
  <rejected> \node_modules\dlivetv-unofficial-api\index.js:1
  import DliveInit from './dliveInit'
         ^^^^^^^^^
```

**Comment by timedotcc** [comment] 2019-04-24 16:43
babel-node app.js withour "npx".

**Comment by Banonevar** [comment] 2019-04-24 16:45
Same
```
babel-node app.js
Mongodb connected
server listening on http://0.0.0.0:3000
Unhandled Rejection at:  Promise {
  <rejected> D:\Projects\icedragon\libs\dlive.js:1
  import Dlive from 'dlivetv-unofficial-api';
```

**Comment by Banonevar** [comment] 2019-04-24 16:46
Same
```
 babel-node app.js
  <rejected> \node_modules\dlivetv-unofficial-api\index.js:1
  import DliveInit from './dliveInit'
         ^^^^^^^^^
```

**Comment by timedotcc** [comment] 2019-04-24 16:48
I can't reproduce your problem.

```
H:\GitHub\dlivetv-unofficial-api>babel-node test.js
Joining dlive-*
```

**Comment by Banonevar** [comment] 2019-04-24 16:58
i used it like 
```javascript
const Dlive = require('dlivetv-unofficial-api')
const _ = require('lodash')
const config = require('../config.json')

class Dl {
  constructor() {
    this.start()
  }
  async start () {
    this.client = new Dlive(config.dlive.channel, config.dlive.bot_token)
    this.loadListeners()
  }
  async loadListeners () {
    this.client.on('ChatText', async (object) => {
      if (object.content.startsWith('!'))  {
        require('./message').prepareCommand(object.content.split(' ')[0], object.content)
      }
    })
   
  }
}

module.exports = new Dl()
```

**Comment by Carbowix** [comment] 2019-04-24 16:59
Sorry for inconvenience, I'm aware of the issue and it'll be fixed in the next version along with some new updates.

**Comment by Banonevar** [comment] 2019-04-24 17:02
Thx for answers guys! @Carbowix @timedotcc

**Closed** 2019-04-24 18:08 UTC
Labels: help wanted
